version: '3'
services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

# docker build . -f Dockerfile.dev
# docker run -it <image_id> npm run test
# this wont update accordingly

# 1. docker-compose up
# docker ps
# docker exec -it <container_id> npm run test
# this will update changes live
# and can type in command

# 2. add text suite in docker-compose.yml
# the above command will respond accordingly to changes because of volume
# but cannot type command

# docker exec -it <container_id> sh
# go into shell mode
# 'ps' -> list out processes